//! URef Subgroup
//! 
//! Subgroup U_ref of order 2048 generated by 11 commuting involutions.
//! These act as XOR masks on the lattice index representation.

use crate::lattice::LatticeElement;
use serde::{Deserialize, Serialize};
use std::fmt;

/// URef subgroup with 11 commuting involutions
#[derive(Clone, Serialize, Deserialize)]
pub struct URef {
    pub generators: [u64; 11],
}

impl URef {
    /// Canonical U_ref generators (powers of 2)
    pub fn canonical() -> Self {
        Self {
            generators: [
                1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024,
            ],
        }
    }

    /// Apply involution mask to lattice element
    pub fn apply(&self, element: LatticeElement, mask: u16) -> LatticeElement {
        let mut index = element.to_index();
        for i in 0..11 {
            if (mask & (1 << i)) != 0 {
                index ^= self.generators[i] as usize;
            }
        }
        LatticeElement::from_index(index % LatticeElement::SIZE)
    }

    /// Generate full orbit of an element
    pub fn orbit(&self, element: LatticeElement) -> Vec<LatticeElement> {
        let mut orbit = Vec::with_capacity(2048);
        for mask in 0..2048u16 {
            orbit.push(self.apply(element, mask));
        }
        orbit
    }

    /// Check if element is fixed by any non-trivial involution
    pub fn has_fixed_point(&self, element: LatticeElement) -> bool {
        for i in 1..11 {
            let mask = 1u16 << i;
            if self.apply(element, mask) == element {
                return true;
            }
        }
        false
    }

    /// Compute orbit representative (minimum index)
    pub fn representative(&self, element: LatticeElement) -> LatticeElement {
        self.orbit(element)
            .into_iter()
            .min_by_key(|e| e.to_index())
            .unwrap_or(element)
    }
}

impl fmt::Debug for URef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "URef(generators={:?})", self.generators)
    }
}

/// Involution certificate
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvolutionCertificate {
    pub generator_index: usize,
    pub mask: u16,
    pub element: LatticeElement,
    pub result: LatticeElement,
    pub is_identity: bool,
}

impl InvolutionCertificate {
    /// Verify involution property (applying twice = identity)
    pub fn verify(uref: &URef, generator_index: usize) -> Vec<Self> {
        let mask = 1u16 << generator_index;
        let mut certs = Vec::new();
        
        // Sample 256 elements to verify
        for i in 0..256 {
            let elem = LatticeElement::from_index(i * 48);
            let result1 = uref.apply(elem, mask);
            let result2 = uref.apply(result1, mask);
            
            certs.push(Self {
                generator_index,
                mask,
                element: elem,
                result: result1,
                is_identity: result2 == elem,
            });
        }
        
        certs
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_canonical_uref() {
        let uref = URef::canonical();
        assert_eq!(uref.generators.len(), 11);
    }

    #[test]
    fn test_apply() {
        let uref = URef::canonical();
        let elem = LatticeElement::new(0, 0);
        let result = uref.apply(elem, 1); // XOR with 1
        assert_eq!(result.b, 1);
    }

    #[test]
    fn test_orbit_size() {
        let uref = URef::canonical();
        let elem = LatticeElement::new(0, 0);
        let orbit = uref.orbit(elem);
        assert_eq!(orbit.len(), 2048);
    }

    #[test]
    fn test_involution_property() {
        let uref = URef::canonical();
        let elem = LatticeElement::new(5, 100);
        let mask = 1u16 << 3; // generator 3
        let result1 = uref.apply(elem, mask);
        let result2 = uref.apply(result1, mask);
        assert_eq!(elem, result2); // involution: applying twice = identity
    }
}
